<?php

// Disable deactivation emails 
// based highly off: 
// http://drupal.stackexchange.com/questions/32413/how-can-i-allow-users-to-cancel-their-accounts-without-requiring-e-mail-confirma

/*
 * Implements hook_menu().
 */ 
function disable_cancel_confirm_email_menu() {
  variable_set('user_mail_cancel_confirm_notify', false);
}



function disable_cancel_confirm_email_form_user_cancel_confirm_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'disable_cancel_confirm_email_user_cancel_form_submit';
}

function disable_cancel_confirm_email_user_cancel_form_submit(&$form, &$form_state) {
  // Rather than negating the complex access expression from the original form we can
  // just make the change in the else portion

  global $user;
  $account = $form_state['values']['_account'];
  if (user_access('administer users') && empty($form_state['values']['user_cancel_confirm']) && $account->uid != $user->uid) {
    // Account has already been cancelled by the system.
  }
  else {
    // Cancel the account
    user_cancel($form_state['values'], $account->uid, $form_state['values']['user_cancel_method']);
    
    // Clear the message queue and say the account is deactivated
    drupal_get_messages();  
    //drupal_set_message(t('Your account has been canceled.'), 'message');

    // We don't want to go to the user profile page, just go to the front
    // drupal_goto('<front>');
  
  }
}

